session_name: cihai-handbook
start_directory: ./
shell_command_before:
  - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
  - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
  - '[ ! -d .env/build ] || rm -rf .env/build'
windows:
- window_name: cihai-handbook
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before: 
    - command -v virtualenv >/dev/null 2>&1 || { pip install virtualenv; }
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate || virtualenv .env'
    - '[ ! -d .env/build ] || rm -rf .env/build'
    - command -v .env/bin/vcspull >/dev/null 2>&1 || { pip install -e .; }
  panes:
  - shell_command:
    - reset
    - vim
    - :Ex
  - pwd
  - echo 'docs built to <http://0.0.0.0:8014/_build/html>'; python -m SimpleHTTPServer 8014
  - shell_command:
    - command -v sphinx-quickstart >/dev/null 2>&1 || { pip install -r requirements.pip; }
    - command -v watching_testrunner >/dev/null 2>&1 || { pip install watching_testrunner; }
    - watching_testrunner --basepath ./ --pattern="*.rst" 'make html'
    - python -m SimpleHTTPServer
