session_name: cihai-handbook
start_directory: ./
before_script: ./bootstrap_env.py
windows:
- window_name: cihai-handbook
  layout: main-horizontal
  options:
    main-pane-height: 35
  shell_command_before: 
    - '[ -d .env -a -f .env/bin/activate ] && source .env/bin/activate'
  panes:
  - pane
  - pane
  - echo 'docs built to <http://0.0.0.0:8014/_build/html>'; python -m SimpleHTTPServer 8014
  - watching_testrunner --basepath ./ --pattern="*.rst" 'make html'


